### ISSUE TITLE
getBlocks() starts at the -, - world border instead of 0, 0

### ISSUE THREAD

**Issue by Red-exe-Engineer** [Bigjango13/MCPI-Addons#2] opened 2022-08-14 22:13 UTC

**Comment by Bigjango13** [comment] 2022-08-15 01:24
Does this happen with `getBlocks3D` too? `getBlocks` is just a wrapper that flattens the list.

**Comment by Bigjango13** [comment] 2022-08-15 01:46
I cannot reproduce this, it can't be a wrong version problem because `getBlocks` was added in the newest version. Could you send the steps to reproduce?

**Comment by Bigjango13** [comment] 2022-08-15 02:49
I have found and fixed it, the fix will be in v1.2.0. Thanks for reporting it.

**Comment by Bigjango13** [comment] 2022-11-27 02:46
Fixed in 285dfb0.

**Closed as completed by Bigjango13** 2022-11-27 02:46 UTC
Labels: bug, Fixed in future update
